### ISSUE TITLE
Minor Refactoring Required

### ISSUE THREAD

**Issue by mohdomama** [Vibatious/svg-viewer#1]
Add Line Break:
https://github.com/Vibatious/svg-viewer/blob/142a9ac8aa0ca177a1e56ac45158fbc1550a682b/svg_preview.js#L39

Add Line Break:
https://github.com/Vibatious/svg-viewer/blob/142a9ac8aa0ca177a1e56ac45158fbc1550a682b/svg_preview.js#L10

Add Line Break:
https://github.com/Vibatious/svg-viewer/blob/142a9ac8aa0ca177a1e56ac45158fbc1550a682b/svg_preview.js#L7

Add Line Break:
https://github.com/Vibatious/svg-viewer/blob/142a9ac8aa0ca177a1e56ac45158fbc1550a682b/svg_preview.js#L4

**Comment by Vibatious** [comment]
Thanks for advice
